name: Continuous Delivery - Autopilot LUA

on:
  release:
    types: [published]

env:
  PROJECT: "autopilot"

jobs:
  release:
    runs-on: windows-latest
    env:
      BUNDLE_FILE_NAME: "autopilot.zip"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Bundle  
      shell: pwsh
      run: |
        $excludeDirs = @('.github','.vscode','definitions','utils')
        $releaseDir = $env:PROJECT + "\"
        $Directories = Get-ChildItem -Directory "." -Exclude $excludeDirs 

        function CopyReleaseContents($parentDir, $directories){

            foreach($dir in $directories) {
                $currentDir = ($parentDir + $dir.Name + "\")
                $childReleaseDir = ($releaseDir + $currentDir)
                New-Item -Path $childReleaseDir -ItemType Directory
                Copy ($currentDir + "*.lua") $childReleaseDir 


                $ChildDirectories = Get-ChildItem -Directory $dir.Name 
                CopyReleaseContents ($currentDir+"\") $ChildDirectories

            }
        }

        New-Item -Path $releaseDir -ItemType Directory
        Copy "*.lua" $releaseDir
        CopyReleaseContents '.\' $Directories

        7z a -tzip $env:BUNDLE_FILE_NAME -r ($env:PROJECT + "/*.lua")
        7z a -tzip $env:BUNDLE_FILE_NAME utils/*.lua

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: autopilot.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/easy-zip-files        